// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsJiEC0N8bQuSUKOOWRvBTaZP3_DulSpg',
    appId: '1:1023568811212:web:efa3977538c345c8501e69',
    messagingSenderId: '1023568811212',
    projectId: 'cyclops-a2877',
    authDomain: 'cyclops-a2877.firebaseapp.com',
    storageBucket: 'cyclops-a2877.appspot.com',
    measurementId: 'G-BZFPWFTEBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__1Pxpx6E2TSZiIRBPA2hkQFqzvXBXhY',
    appId: '1:1023568811212:android:a21e137df929d886501e69',
    messagingSenderId: '1023568811212',
    projectId: 'cyclops-a2877',
    storageBucket: 'cyclops-a2877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-XTQqLP8xYQV6kB8iZprG1RCU7yObAbw',
    appId: '1:1023568811212:ios:10c3420f0aa0db5f501e69',
    messagingSenderId: '1023568811212',
    projectId: 'cyclops-a2877',
    storageBucket: 'cyclops-a2877.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-XTQqLP8xYQV6kB8iZprG1RCU7yObAbw',
    appId: '1:1023568811212:ios:2e8f2035454169e1501e69',
    messagingSenderId: '1023568811212',
    projectId: 'cyclops-a2877',
    storageBucket: 'cyclops-a2877.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
